#!/bin/expect

set PW "ToBeUpdated_DBAdmPwd"
set DBHOST "ToBeUpdated_DBSystemIP"
set SRVNAME "ToBeUpdated_DBSrv"
set Prompt "\[#$%>\]"
set timeout 60

spawn env LANG=C java -jar ords.war validate

expect {
    -re "Enter the name of the database server \\\[.*\\\]:" {
        send -- "${DBHOST}\n"
    }
}

expect {
    -glob "Enter the database listen port \\\[1521\\\]:" {
        send -- "\n"
    }
}

expect {
    -re "Enter the database service name \\\[.*\\\]:" {
        send -- "${SRVNAME}\n"
    }
    "Enter the database service name:" {
        send -- "${SRVNAME}\n"
    }
}

expect {
    -glob "Enter the database password for SYS AS SYSDBA:" {
        send -- "${PW}\n"
        exp_continue
    }
    -glob "Confirm password:" {
        send -- "${PW}\n"
    }
}

expect {
    -glob "${Prompt}" {
        interact
        exit 0
    }
}
